# Generated by Django 6.0.3 on 2026-03-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newarrivals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newarrivals',
            name='image',
            field=models.ImageField(upload_to='arrivals/'),
        ),
    ]
