# Generated by Django 6.0.3 on 2026-03-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='email',
            field=models.CharField(unique=True),
        ),
    ]
